### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by bdany70** [bdany70/SEBC#1]

**Comment by bdany70** [comment]
Created last step 3_cm_installed.png

**Comment by bdany70** [comment]
Created optional step 4_local_repo

**Comment by cfusi** [comment]
Good job!
Please do not neglect to check also the reverse lookup.
Here you can find a reference:
https://www.cloudera.com/documentation/other/reference-architecture/topics/ra_bare_metal_deployment.html#concept_aj4_g4l_f2b
